### ISSUE TITLE
Delete d un issuer externe ne fonctionne plus

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/wallet-provider#169]

**Comment by patatoid** [comment]
https://github.com/TalaoDAO/wallet-provider/commit/7be7a218384fe058283f2769f1f269372520ed41 waiting for preprod deployment

**Comment by patatoid** [comment]
Available in preprod

**Comment by ThierryThevenet** [comment]
on ne peut plus accéder a l external issuer
