### ISSUE TITLE
Add sd-jwt type in external issuer form

### ISSUE THREAD

**Issue by ThierryThevenet** [TalaoDAO/wallet-provider#176]

**Comment by patatoid** [comment]
![Capture d’écran de 2024-05-14 15-58-53](https://github.com/TalaoDAO/wallet-provider/assets/5272186/3b8c04d8-74aa-4d6f-899a-50fdd89a3365)

**Comment by patatoid** [comment]
https://github.com/TalaoDAO/wallet-provider/commit/dc879664fc5c14f50380bce1affa861b9180f807

To be released

**Comment by patatoid** [comment]
Available in preprod
